//proposal
export const PROPOSAL_CHANGE_STEP = 'PROPOSAL_CHANGE_STEP';
export const PROPOSAL_CHANGE_SUCCESS = 'PROPOSAL_CHANGE_SUCCESS';
export const PROPOSAL_FORM_SHOW = "PROPOSAL_FORM_SHOW";
export const PROPOSAL_FORM_HIDE = "PROPOSAL_FORM_HIDE";
export const PROPOSAL_REQUEST_STARTED = "PROPOSAL_REQUEST_STARTED";
export const PROPOSAL_REQUEST_SUCCESS = "PROPOSAL_REQUEST_SUCCESS";
export const PROPOSAL_REQUEST_FAILURE = "PROPOSAL_REQUEST_FAILURE";
//popup
export const POPUP_SHOW = 'POPUP_SHOW';
export const POPUP_HIDE = 'POPUP_HIDE';
//partners
export const ADD_PARTNER = "ADD_PARTNER";
export const SHOW_ALL_PARTNERS = "SHOW_ALL_PARTNERS";
//question form
export const TOGGLE_ANSWER_SHOW = "TOGGLE_ANSWER_SHOW";
export const FAQ_LOAD_REQUEST = "FAQ_LOAD_REQUEST";
export const FAQ_LOAD_SUCCESS = "FAQ_LOAD_SUCCESS";
export const FAQ_LOAD_FAILURE = "FAQ_LOAD_FAILURE";